

fos_user_security_login:
    path:  /admin/login
    defaults: { _controller: FOSUserBundle:Security:login }

fos_user_security_check:
    path:  /admin/check
    defaults: { _controller: FOSUserBundle:Security:check }

fos_user_security_logout:
    path:  /admin/logout
    defaults: { _controller: FOSUserBundle:Security:logout }

paprec_home:
    resource: "@PaprecHomeBundle/Controller/"
    type:     annotation
    prefix:   /admin

paprec_user:
    resource: "@PaprecUserBundle/Controller/"
    type:     annotation
    prefix:   /admin/user
