services:
  _defaults: { public: true }

  paprec_catalog.category_manager:
    class: Paprec\CatalogBundle\Service\CategoryManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.product_di_manager:
    class: Paprec\CatalogBundle\Service\ProductDIManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.product_chantier_manager:
    class: Paprec\CatalogBundle\Service\ProductChantierManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

parameters:

  paprec_catalog.category.picto_path: "%kernel.root_dir%/../web/uploads/pictos"
  paprec_catalog.argument.picto_path: "%kernel.root_dir%/../web/uploads/pictos"
  paprec_catalog.product.di.picto_path: "%kernel.root_dir%/../web/uploads/pictos"
  paprec_catalog.product.chantier.picto_path: "%kernel.root_dir%/../web/uploads/pictos"
  paprec_catalog.product.d3e.picto_path: "%kernel.root_dir%/../web/uploads/pictos"

  paprec_types_picture:
    - Picto
    - Picture
    - PilotPicture


