<?php

namespace Paprec\CatalogBundle\Repository;

/**
 * GrilleTarifD3ERepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrilleTarifD3ERepository extends \Doctrine\ORM\EntityRepository
{
}
