services:
#    paprec_commercial.example:
#        class: Paprec\CommercialBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  paprec_catalog.product_di_order_manager:
    class: Paprec\CommercialBundle\Service\ProductDIOrderManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

parameters:
  #parameter_name: value


  paprec_order_status:
  - Créé
  - En attente
  - Traité
  - Clos