services:
#    paprec_commercial.example:
#        class: Paprec\CommercialBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

  paprec_catalog.product_di_quote_manager:
    class: Paprec\CommercialBundle\Service\ProductDIQuoteManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.product_chantier_quote_manager:
    class: Paprec\CommercialBundle\Service\ProductChantierQuoteManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

  paprec_catalog.product_chantier_order_manager:
    class: Paprec\CommercialBundle\Service\ProductChantierOrderManager
    arguments: ["@doctrine.orm.entity_manager", "@service_container"]

parameters:
  paprec_commercial.quote_request.files_path: "%kernel.root_dir%/../web/uploads/files"
  paprec_commercial.product_chantier_order.files_path: "%kernel.root_dir%/../web/uploads/files/invoices"



  paprec_quote_status:
  - Créé
  - En attente
  - Traité
  - Clos

  paprec_order_status:
  - Créée
  - En attente
  - Payée
  - Annulée

  paprec_order_payment_methods:
  - CB
  - Virement
  - E-signature
  - Courrier
