<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductDIOrderLineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDIOrderLineRepository extends \Doctrine\ORM\EntityRepository
{
}
