<?php

namespace Paprec\CommercialBundle\Repository;

/**
 * ProductDIOrderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductDIOrderRepository extends \Doctrine\ORM\EntityRepository
{
}
